Cleaup readme
giantswarm/aws-load-balancer-controller-app pull request #75
Opened 2023-04-04 12:02 UTC by mleisa

- **This repository allows merge commits, if you're creating a Release, make sure to select 'Squash and merge'**
- **When merging subtree updates, it is important to select 'Create a merge commit' when merging.**

This PR updates README.md with
- cleanup
- add upstream doc
- info about k8s ingress

2023-04-04 12:18 UTC, ubergesundheit commented on README.md
> +If your use case does not require an NLB, consider using the Kubernetes In-Tree [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) instead of the AWS Load Balancer Controller
Maybe I'm wrong but I've never seen aws lb annotations on Ingress objects. Always Services (which are backing Ingress objects)

I think you should link to Giant Swarm docs. [This page](https://docs.giantswarm.io/advanced/ingress/service-type-loadbalancer/#customizing-the-external-load-balancer) partially handles AWS load balancers

2023-04-04 12:19 UTC, ubergesundheit commented on README.md
> +If your use case does not require an NLB, consider using the Kubernetes In-Tree [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) instead of the AWS Load Balancer Controller
Never used AWS ALBs though. Maybe it works with Ingresses?

2023-04-04 12:21 UTC, ubergesundheit commented on README.md
> +```bash
Can you check if this is still required? I think newer Giant Swarm platform releases have this stuff pre-configured.

To check: Create a test cluster with a new-ish platform release version on AWS, install this app, Add a Service with some AWS load-balancer-controller annotation, then check the logs of the aws load-balancer-controller pods to see if there are any errors.
If you want, we can pair on this

2023-04-04 12:50 UTC, mcharriere commented on README.md
> +**Note**: Deployed chart does not receive security updates automatically. You need to manually upgrade to a newer chart.
not sure what this means. I'd probably delete it (chart updates are a matter of updating the app, as the rest of our apps.)

2023-04-04 12:51 UTC, mcharriere commented on README.md
> +[AWS Load Balancer](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) controller manages the following AWS resources
```suggestion
[AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/) manages the following AWS resources
```

2023-04-04 12:58 UTC, mcharriere commented on README.md
> +If your use case does not require an NLB, consider using the Kubernetes In-Tree [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) instead of the AWS Load Balancer Controller
> As things are a bit trickier.

Let me elaborate:
- the `in-tree` and the `cloud-controller` implementations are feature equivalent. Both are frozen when it comes to Load balancer features.
- The `in-tree` and the cloud-controller` implementations support Classic LBs and partially NLBs. 
- Any new development/feature goes to the `aws-load-balancer-controller`
- The `aws-load-balancer-controller` supports NLBs (services) and ALBs (ingresses). NLB support here is more complete than the other 2 implementations.

Eventually we would need to make this app a default app for AWS, so I don't think it's worth to discourage its usage .

2023-04-04 13:13 UTC, mleisa commented on README.md
> +If your use case does not require an NLB, consider using the Kubernetes In-Tree [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) instead of the AWS Load Balancer Controller
I wasn't aware of the difference between `in-tree` and `cloud-controller`, thanks for that

Taking what @mcharriere said into consideration, it doesn't seem future-proof to promote the usage of just the kubernetes ingress over `aws-load-balancer-controller`, so I will remove that part

2023-04-05 13:37 UTC, mleisa commented on README.md
> +```bash
Are CAPA clusters already in usage? If yes, I'll add a note that it's required on CAPA

2023-04-11 12:48 UTC, Gacko requested changes
Basically fine, but either we do not tell "it's not required for Vintage, only for CAPI" regarding the IAM stuff or we double check the current situation.

IIRC `kiam` is not in use any more for newer AWS releases, so probably and especially not for CAPI. This does not make a difference since you still need to create the role, it only changes the way this role is getting assumed.

Last but not least I'd rather be safe than sorry and ask the user to always ensure the role. Doesn't hurt...

2023-04-11 12:48 UTC, Gacko commented on README.md
> +```bash
I'm not sure if the role has been created by someone else manually and not been deleted or if it's really created automatically... would double check this.

2023-04-11 12:48 UTC, Gacko commented on README.md
> +
```suggestion
```

2023-04-11 13:45 UTC, mcharriere commented on README.md
> +```bash
on vintage, the role is created by https://github.com/giantswarm/aws-operator/blob/master/service/controller/resource/tccpn/template/template_main_iam_policies.go
On CAPA the role is not created at all, thus giantswarm/giantswarm#26467

2023-04-11 13:48 UTC, Gacko approved these changes

2023-04-11 14:50 UTC, merged