Add VPA
giantswarm/aws-load-balancer-controller-app pull request #87
Opened 2023-06-19 13:07 UTC by paurosello

- **This repository allows merge commits, if you're creating a Release, make sure to select 'Squash and merge'**
- **When merging subtree updates, it is important to select 'Create a merge commit' when merging.**

This PR..

2023-06-19 13:11 UTC, Gacko requested changes
Please regenerate the `values.schema.json`. Everything else LGTM! :)

2023-06-19 13:11 UTC, Gacko commented on helm/aws-load-balancer-controller/templates/vpa.yaml
> +{{ end }}
```suggestion
{{ end }}
```

2023-06-30 07:57 UTC, paurosello commented on helm/aws-load-balancer-controller/templates/vpa.yaml
> +{{ end }}
when regenerating schema values all hell breaks loose as many fields are set to Null

2023-06-30 08:33 UTC, paurosello commented
not doing the schema update as it will mess a bunch of fields now

2023-06-30 08:35 UTC, T-Kukawka approved these changes

2023-06-30 08:57 UTC, pipo02mix approved these changes
LGTM though I did not test it

2023-06-30 09:07 UTC, LolloneS commented
I fear the installation could fail because of the "wrong" schema, is it tested?

2023-06-30 09:12 UTC, paurosello commented
The schema did not change, I did not add/modify any value on the values.yaml file so I expect it to work, doing some tests anyway

2023-06-30 09:12 UTC, merged